### ISSUE TITLE
Tracking: removal of IFD in modules

### ISSUE THREAD

**Issue by getchoo** [catppuccin/nix#392]
[Import from derivation](https://nix.dev/manual/nix/2.25/language/import-from-derivation.html) is a cool and very helpful feature of Nix, but can seriously hurt evaluation performance, and may not be allowed in some cases. We should try to avoid it when possible (in a reasonable way)

Modules that currently require IFD include:

- [x] cava https://github.com/catppuccin/nix/issues/376, https://github.com/catppuccin/nix/pull/750
- [ ] firefox
- [ ] fzf
- [ ] gh-dash
- [ ] imv https://github.com/catppuccin/nix/issues/375
- [x] lazygit https://github.com/catppuccin/nix/pull/604
- [x] mako https://github.com/catppuccin/nix/issues/341, https://github.com/catppuccin/nix/pull/684
- [x] sioyek https://github.com/catppuccin/nix/pull/686
- [ ] starship
- [ ] skim
- [ ] swaylock https://github.com/catppuccin/nix/issues/340
- [ ] tty
- [x] wezterm
- [ ] gemini-cli

**Comment by mightyiam** [comment]
Would it still be IFD if sources are flake inputs?

**Comment by getchoo** [comment]
No, but for the same reason https://github.com/catppuccin/nix/pull/377 prevents IFD. Flake inputs use builtin fetchers, which would still block evaluation for every port download

See also https://github.com/catppuccin/nix/issues/388

**Comment by stasjok** [comment]
I've got 'allow-import-from-derivation' error after updating from here:

https://github.com/catppuccin/nix/blob/8b6baed3d010416da6295805012b12cfa05c09f7/modules/home-manager/fzf.nix#L8

Searching 'importJSON' I found similar usages. Those modules can be added here I think.

**Comment by multivac61** [comment]
Getting errors in CI after recent update.

**Comment by getchoo** [comment]
Thanks for catching these, The list has been updated 👍

**Comment by isabelroses** [comment]
As a note I would recommend just disabling starship if you have issues with IFD since starship should match your terminal colours.

**Comment by getchoo** [comment]
IFD was re-introduced in the lazygit module with https://github.com/catppuccin/nix/pull/515

**Comment by mightyiam** [comment]
In case anyone cares about `nix flake show` as much as I do, [stylix](https://stylix.danth.me/) does not inherently involve IFD.

[Here's how I have migrated from using catppuccin-nix to apply catppuccin to using stylix to apply catppuccin](https://github.com/mightyiam/infra/commit/4a2f58326fbed6e06656decfd3cdc63d71ee61a3#diff-f532d278aef953f5b83d8433129bb382f817d6df4b0afaa6401eec169dc04ca7R4).

**Comment by alejandro-angulo** [comment]
I think I have a fix for the lazygit IFD https://github.com/catppuccin/nix/pull/604

**Comment by alejandro-angulo** [comment]
I was looking into the fzf module and I wonder if a `palette.nix` file should be generated (based off the JSON we get from the palette package) and we can import that rather than having to read JSON.

So we could possibly do something like

```nix
prorgrams.fzf.colors."bg+" = lib.palette."${config.catppuccin.flavor}".colors."${config.catppuccin.acent}".surface0
```
The fzf port provides a shell file that we could have ran as part of shell startup but I'm not sure there's a shell agnostic way of defining commands to run/envvars to export.

**Comment by getchoo** [comment]
> In case anyone cares about `nix flake show` as much as I do

Small update: as of Nix 2.29, [`nix flake show` works correctly with IFD](https://github.com/NixOS/nix/pull/12583)

**Comment by isabelroses** [comment]
as of https://github.com/catppuccin/nix/pull/686 sioyek no longer sans ifd

**Comment by Anomalocaridid** [comment]
Shouldn't tty and skim also be on the list since they both rely on importing the palette?

**Comment by Anomalocaridid** [comment]
> I was looking into the fzf module and I wonder if a `palette.nix` file should be generated (based off the JSON we get from the palette package) and we can import that rather than having to read JSON.
> 
> So we could possibly do something like
> 
> prorgrams.fzf.colors."bg+" = lib.palette."${config.catppuccin.flavor}".colors."${config.catppuccin.acent}".surface0


Building off of this idea, maybe we could create a separate port that was a library flake for nix that only provided a color palette? We already have similar libraries for other languages, so it wouldn't be unprecedented. We could use whiskers to generate it and avoid needing IFD. 

This way, rather than importing the palette JSON file and requiring IFD for some modules, we could just pull in the palette flake as an input and use that. (At least until we find ways to use the upstream ports directly, of course.)

This would also have the added benefit of providing a convenient way to access catppuccin's color palette in nix configs for users that want it (#96, #167, #285, #348, #464, #554) without us having to worry about maintaining a public api for it here.

> The fzf port provides a shell file that we could have ran as part of shell startup but I'm not sure there's a shell agnostic way of defining commands to run/envvars to export.

fzf at some point added [`$FZF_DEFAULT_OPT_FILE`](https://github.com/junegunn/fzf?tab=readme-ov-file#environment-variables) which should provide a way to avoid IFD. I already plan on making a PR to add support for it to the upstream fzf port and then making a PR to implement it here.

**Comment by Anomalocaridid** [comment]
> I like this idea, so here's my attempt: [#738](https://github.com/catppuccin/nix/pull/738)

I meant creating a library flake in a separate repo and [submitting it as a port](https://github.com/catppuccin/catppuccin/blob/main/docs/port-creation.md).

The maintainers of this repo consider exposing a palette here to be out of scope. (See #96 and #167 for explanations why.)

**Comment by musjj** [comment]
What would the port even be called? `nix` is obviously taken by this repo already. I feel like this repo would be the best place for the palette, considering the prior art:

- https://github.com/catppuccin/python
- https://github.com/catppuccin/go
- https://github.com/catppuccin/rust
- etc.

**Comment by Anomalocaridid** [comment]
> What would the port even be called? `nix` is obviously taken by this repo already.

It would probably be called something like `nix-palette` or `nix-library`.

> I feel like this repo would be the best place for the palette, considering the prior art:
> 
>     * https://github.com/catppuccin/python
> 
>     * https://github.com/catppuccin/go
> 
>     * https://github.com/catppuccin/rust
> 
>     * etc.

It would make sense, and you are far from the first person to suggest something like this, but the maintainers of this port have already decided this port should solely focus on applying existing themes. Rather than also providing the means to make new ones, which would add the burden of maintaining a stable api for it.

Hence my suggestion of a separate, standalone port for the palette as a compromise. This way, both ports can focus on just one thing.

Also considering that nix is primarily for configuration management rather than a general-purpose programming language, I would argue that it could be considered a special case compared to Python Go, Rust, etc.

Speaking of prior art, it would not be entirely unprecedented for there to be multiple ports for the same thing, where each port covers a separate aspect of theming:

* https://github.com/catppuccin/zed
* https://github.com/catppuccin/zed-icons

**Comment by no-mood** [comment]
Is this why `nix flake check --no-build` breaks? I use it as a commit hook, and without a full check, catppuccin throws an error
